/**
 * Thin GitHub REST API client for Eng Stats.
 * All functions accept a PAT and return typed responses.
 * Handles rate-limit headers and Link-header pagination.
 */

// ─── GitHub API response shapes ───

export interface GHPull {
  number: number;
  title: string;
  body: string | null;
  created_at: string;
  merged_at: string | null;
  state: string;
  head: { ref: string };
}

export interface GHPRDetail {
  number: number;
  additions: number;
  deletions: number;
  changed_files: number;
}

export interface GHReview {
  submitted_at: string;
  state: string;
}

export interface GHCommit {
  commit: {
    message: string;
  };
}

export interface GHRelease {
  published_at: string;
}

export interface GHCopilotMetric {
  date: string;
  total_active_users: number;
  total_engaged_users: number;
  copilot_ide_chat?: {
    total_chats?: number;
  };
}

// ─── Internal fetch helper ───

async function ghFetch<T>(token: string, path: string): Promise<T[]> {
  const results: T[] = [];
  let url: string | null = `https://api.github.com${path}`;

  while (url) {
    const resp = await fetch(url, {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
    });

    if (!resp.ok) {
      const text = await resp.text().catch(() => "");
      throw new Error(`GitHub API ${resp.status}: ${text}`);
    }

    const page = (await resp.json()) as T[];
    results.push(...page);

    // Follow Link: <url>; rel="next" pagination
    const link = resp.headers.get("Link") ?? "";
    const next = link.match(/<([^>]+)>;\s*rel="next"/);
    url = next ? next[1] : null;
  }

  return results;
}

async function ghFetchOne<T>(token: string, path: string): Promise<T> {
  const resp = await fetch(`https://api.github.com${path}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
  });

  if (!resp.ok) {
    const text = await resp.text().catch(() => "");
    throw new Error(`GitHub API ${resp.status}: ${text}`);
  }

  return resp.json() as Promise<T>;
}

// ─── Public API ───

/** Fetch closed (merged) PRs since the given ISO date string */
export async function fetchMergedPRs(
  token: string,
  repo: string,
  since: string,
): Promise<GHPull[]> {
  const pulls = await ghFetch<GHPull>(
    token,
    `/repos/${repo}/pulls?state=closed&per_page=100&sort=updated&direction=desc`,
  );
  return pulls.filter(
    (p) => p.merged_at !== null && p.merged_at >= since,
  );
}

/** Fetch additions/deletions/changed_files for a specific PR */
export async function fetchPRDetails(
  token: string,
  repo: string,
  prNumber: number,
): Promise<GHPRDetail> {
  return ghFetchOne<GHPRDetail>(token, `/repos/${repo}/pulls/${prNumber}`);
}

/** Fetch all reviews for a PR */
export async function fetchPRReviews(
  token: string,
  repo: string,
  prNumber: number,
): Promise<GHReview[]> {
  return ghFetch<GHReview>(token, `/repos/${repo}/pulls/${prNumber}/reviews`);
}

/** Fetch commits for a PR (used for AI signature scanning) */
export async function fetchPRCommits(
  token: string,
  repo: string,
  prNumber: number,
): Promise<GHCommit[]> {
  return ghFetch<GHCommit>(token, `/repos/${repo}/pulls/${prNumber}/commits`);
}

/** Fetch recent releases for deploy-frequency metric */
export async function fetchReleases(
  token: string,
  repo: string,
): Promise<GHRelease[]> {
  return ghFetch<GHRelease>(token, `/repos/${repo}/releases?per_page=30`);
}

/** Fetch Copilot org-level daily metrics (requires read:org scope) */
export async function fetchCopilotMetrics(
  token: string,
  org: string,
): Promise<GHCopilotMetric[]> {
  return ghFetch<GHCopilotMetric>(token, `/orgs/${org}/copilot/metrics`);
}

// ─── AI tool detection ───

const AI_PATTERNS: Array<{ tool: string; patterns: RegExp[] }> = [
  {
    tool: "claude",
    patterns: [
      /co-authored-by:.*claude/i,
      /🤖 generated with claude code/i,
      /noreply@anthropic\.com/i,
    ],
  },
  {
    tool: "cursor",
    patterns: [
      /co-authored-by:.*cursor/i,
      /generated by cursor/i,
      /cursor\.sh/i,
    ],
  },
  {
    tool: "copilot",
    patterns: [
      /co-authored-by:.*github copilot/i,
      /co-authored-by:.*copilot/i,
    ],
  },
  {
    tool: "devin",
    patterns: [
      /co-authored-by:.*devin/i,
      /app\.devin\.ai/i,
    ],
  },
  {
    tool: "ai",
    patterns: [
      /co-authored-by:.*\bai\b/i,
      /\[ai\]/i,
      /ai-generated/i,
    ],
  },
];

/**
 * Scan PR body and commit messages for known AI tool signatures.
 * Returns deduplicated array of matched tool names.
 */
export function detectAITools(
  prBody: string | null,
  commitMessages: string[],
): string[] {
  const haystack = [prBody ?? "", ...commitMessages].join("\n");
  const found = new Set<string>();

  for (const { tool, patterns } of AI_PATTERNS) {
    if (patterns.some((re) => re.test(haystack))) {
      found.add(tool);
    }
  }

  return Array.from(found);
}
