/**
 * Demo mode fixtures — realistic fake data for presentations.
 * All IDs are negative to avoid collisions with Dexie auto-increment.
 * Dates use relative helpers so data always looks fresh.
 */

import type {
  Commitment,
  Dismissal,
  CompletionSuggestion,
  MorningBrief,
  DecisionLogEntry,
  ConversationMessage,
  Tag,
  Person,
  PersonContext,
  CalendarEvent,
  MemoryEntry,
  WorkPattern,
  WeeklyDigest,
  OKR,
  CommitmentOKRLink,
  ActionProposal,
  DraftMessage,
  FollowUpRule,
  JiraTicket,
  PRJiraLink,
  NewsPost,
  OpenPRSnapshot,
  PRInboxItem,
} from "./types";

// ─── Date helpers ───

function hoursAgo(n: number): string {
  return new Date(Date.now() - n * 3600_000).toISOString();
}

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 86400_000).toISOString();
}

function todayDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function futureHours(n: number): string {
  return new Date(Date.now() + n * 3600_000).toISOString();
}

// ─── Conversation message factories ───

function msgs(...items: [string, string, boolean][]): ConversationMessage[] {
  return items.map(([sender, text, isMine], i) => ({
    sender,
    text,
    timestamp: hoursAgo(items.length - i),
    isMine,
  }));
}

// ─── Demo Tags ───

export const DEMO_TAGS: Tag[] = [
  { id: -1, name: "General", color: "#6B7280", createdAt: daysAgo(7) },
  { id: -2, name: "Engineering", color: "#2563EB", createdAt: daysAgo(7) },
  { id: -3, name: "Sales & Partnerships", color: "#EA580C", createdAt: daysAgo(7) },
  { id: -4, name: "1:1 Follow-ups", color: "#7C3AED", createdAt: daysAgo(7) },
  { id: -5, name: "Platform & Infra", color: "#0891B2", createdAt: daysAgo(7) },
  { id: -6, name: "People & Ops", color: "#DB2777", createdAt: daysAgo(7) },
];

// ─── Demo Commitments ───

export const DEMO_COMMITMENTS: Commitment[] = [
  // ── 5 status "new" ──

  // 3 high urgency → "Needs attention"
  {
    id: -1,
    hash: "demo-001",
    text: "Send revised proposal to Acme Corp by end of day",
    original_quote: "I'll get the revised proposal over to Acme by EOD today",
    deadline: futureHours(4),
    urgency: "high",
    context: "#acme-partnership",
    source_type: "slack",
    confidence: 0.94,
    status: "new",
    direction: "by_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: hoursAgo(3),
    snooze_until: null,
    context_summary: "Discussing updated pricing terms for the Acme Corp deal",
    conversation_messages: msgs(
      ["Jordan Lee", "Hey, any update on the Acme proposal? They're asking.", false],
      ["You", "I'll get the revised proposal over to Acme by EOD today", true],
      ["Jordan Lee", "Perfect, they're expecting it before their 5pm meeting", false],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -3,
    createdAt: hoursAgo(3),
  },
  {
    id: -2,
    hash: "demo-002",
    text: "Review and approve the Q2 budget spreadsheet",
    original_quote: "I'll review the Q2 budget and approve it before the board meeting",
    deadline: futureHours(6),
    urgency: "high",
    context: "#finance",
    source_type: "slack",
    confidence: 0.91,
    status: "new",
    direction: "assigned_to_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: hoursAgo(5),
    snooze_until: null,
    context_summary: "Finance team needs budget sign-off before Thursday board meeting",
    conversation_messages: msgs(
      ["Maria Chen", "Budget spreadsheet is in the shared drive — can you review before Thursday?", false],
      ["You", "I'll review the Q2 budget and approve it before the board meeting", true],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -1,
    createdAt: hoursAgo(5),
  },
  {
    id: -3,
    hash: "demo-003",
    text: "Fix the authentication bug blocking the staging deploy",
    original_quote: "I'll dig into the auth bug right after standup — it's blocking staging",
    deadline: null,
    urgency: "high",
    context: "#engineering",
    source_type: "slack",
    confidence: 0.88,
    status: "new",
    direction: "by_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: hoursAgo(2),
    snooze_until: null,
    context_summary: "Auth token refresh fails intermittently on staging",
    conversation_messages: msgs(
      ["Sam Torres", "Staging deploy is stuck — the auth middleware is throwing 401s on token refresh", false],
      ["You", "I'll dig into the auth bug right after standup — it's blocking staging", true],
      ["Sam Torres", "Thanks, QA is waiting on this one", false],
    ),
    slack_link: null,
    triggered: true,
    sensitive: false,
    tag_id: -2,
    createdAt: hoursAgo(2),
  },

  // 2 medium urgency → "Open"
  {
    id: -4,
    hash: "demo-004",
    text: "Share the competitive analysis deck with the sales team",
    original_quote: "Let me put the competitive analysis together and share it with sales by Friday",
    deadline: daysAgo(-2), // 2 days from now
    urgency: "medium",
    context: "Q2 Planning Offsite",
    source_type: "meeting",
    confidence: 0.85,
    status: "new",
    direction: "by_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: daysAgo(1),
    snooze_until: null,
    context_summary: "Discussed go-to-market strategy for Q2 at the offsite",
    conversation_messages: msgs(
      ["Dana Park", "We need a competitive landscape overview for the sales team", false],
      ["You", "Let me put the competitive analysis together and share it with sales by Friday", true],
      ["Dana Park", "That would be great — they have a big pitch next week", false],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -3,
    createdAt: daysAgo(1),
  },
  {
    id: -5,
    hash: "demo-005",
    text: "Set up the new monitoring dashboard for production",
    original_quote: "I can set up the Grafana dashboard for the new service this week",
    deadline: null,
    urgency: "medium",
    context: "#platform-eng",
    source_type: "slack",
    confidence: 0.82,
    status: "new",
    direction: "by_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: daysAgo(2),
    snooze_until: null,
    context_summary: "Platform team discussing observability for the new microservice",
    conversation_messages: msgs(
      ["Alex Rivera", "We're missing monitoring on the new payment service — anyone have bandwidth?", false],
      ["You", "I can set up the Grafana dashboard for the new service this week", true],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -5,
    createdAt: daysAgo(2),
  },

  // ── 1 status "snoozed" with expired snooze ──
  {
    id: -6,
    hash: "demo-006",
    text: "Follow up with the design team about the onboarding flow",
    original_quote: "I'll follow up with design about the onboarding mockups",
    deadline: null,
    urgency: "medium",
    context: "#product",
    source_type: "slack",
    confidence: 0.79,
    status: "snoozed",
    direction: "by_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: daysAgo(2),
    snooze_until: hoursAgo(1), // expired — should show in active list
    context_summary: "Waiting on new user onboarding flow mockups from the design team",
    conversation_messages: msgs(
      ["Casey Kim", "Design is finishing the onboarding mockups — can someone follow up?", false],
      ["You", "I'll follow up with design about the onboarding mockups", true],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -6,
    createdAt: daysAgo(2),
  },

  // ── 3 status "actioned" (In Progress) ──
  {
    id: -7,
    hash: "demo-007",
    text: "Write the API documentation for the new endpoints",
    original_quote: "I'll write up the API docs for v2 endpoints this sprint",
    deadline: null,
    urgency: "medium",
    context: "#engineering",
    source_type: "slack",
    confidence: 0.90,
    status: "actioned",
    direction: "by_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: daysAgo(3),
    snooze_until: null,
    context_summary: "API v2 launch requires developer documentation",
    conversation_messages: msgs(
      ["Pat Johnson", "Do we have docs for the new v2 endpoints?", false],
      ["You", "I'll write up the API docs for v2 endpoints this sprint", true],
      ["Pat Johnson", "Thanks — external partners are asking for them", false],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -2,
    createdAt: daysAgo(3),
  },
  {
    id: -8,
    hash: "demo-008",
    text: "Prepare the customer success presentation for Thursday",
    original_quote: "I'll have the customer success deck ready for the Thursday all-hands",
    deadline: futureHours(28),
    urgency: "medium",
    context: "1:1 with Jordan",
    source_type: "meeting",
    confidence: 0.87,
    status: "actioned",
    direction: "assigned_to_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: daysAgo(2),
    snooze_until: null,
    context_summary: "Jordan asked for a customer success overview for the all-hands",
    conversation_messages: msgs(
      ["Jordan Lee", "Can you put together a quick customer success overview for Thursday's all-hands?", false],
      ["You", "I'll have the customer success deck ready for the Thursday all-hands", true],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -4,
    createdAt: daysAgo(2),
  },
  {
    id: -9,
    hash: "demo-009",
    text: "Migrate the user table to the new schema",
    original_quote: "I'll handle the user table migration — should be done by Wednesday",
    deadline: null,
    urgency: "high",
    context: "#engineering",
    source_type: "slack",
    confidence: 0.93,
    status: "actioned",
    direction: "by_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: daysAgo(1),
    snooze_until: null,
    context_summary: "Database migration for new user profile fields",
    conversation_messages: msgs(
      ["Sam Torres", "We need the user table migrated before the profile feature ships", false],
      ["You", "I'll handle the user table migration — should be done by Wednesday", true],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -2,
    createdAt: daysAgo(1),
  },

  // ── 3 status "done" (this week) ──
  {
    id: -10,
    hash: "demo-010",
    text: "Merge the accessibility fixes into main",
    original_quote: "I'll get the a11y fixes merged today",
    deadline: null,
    urgency: "medium",
    context: "#engineering",
    source_type: "slack",
    confidence: 0.92,
    status: "done",
    direction: "by_me",
    likely_completed: true,
    completion_signal: "Just merged the a11y PR — all checks pass",
    message_timestamp: daysAgo(1),
    snooze_until: null,
    context_summary: "Accessibility audit follow-up items",
    conversation_messages: msgs(
      ["Casey Kim", "Are the a11y fixes ready to go?", false],
      ["You", "I'll get the a11y fixes merged today", true],
      ["You", "Just merged the a11y PR — all checks pass", true],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -2,
    createdAt: daysAgo(1),
  },
  {
    id: -11,
    hash: "demo-011",
    text: "Send meeting notes from the product sync to stakeholders",
    original_quote: "I'll send the notes out to everyone after this call",
    deadline: null,
    urgency: "low",
    context: "Product Sync",
    source_type: "meeting",
    confidence: 0.86,
    status: "done",
    direction: "by_me",
    likely_completed: true,
    completion_signal: null,
    message_timestamp: daysAgo(2),
    snooze_until: null,
    context_summary: "Weekly product sync — discussed roadmap priorities",
    conversation_messages: msgs(
      ["Dana Park", "Can someone share the notes?", false],
      ["You", "I'll send the notes out to everyone after this call", true],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -1,
    createdAt: daysAgo(2),
  },
  {
    id: -12,
    hash: "demo-012",
    text: "Update the CI pipeline to include the new linting rules",
    original_quote: "I'll update the CI config to run the new ESLint rules",
    deadline: null,
    urgency: "low",
    context: "#platform-eng",
    source_type: "slack",
    confidence: 0.68, // low confidence → "Might be commitments"
    status: "done",
    direction: "by_me",
    likely_completed: true,
    completion_signal: null,
    message_timestamp: daysAgo(3),
    snooze_until: null,
    context_summary: "Discussion about adding stricter lint rules to CI",
    conversation_messages: msgs(
      ["Alex Rivera", "Should we enforce the new lint rules in CI?", false],
      ["You", "I'll update the CI config to run the new ESLint rules", true],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -5,
    createdAt: daysAgo(3),
  },
];

// ── Two items with confidence < 0.75 (added to active list as "Might be commitments") ──
// We'll create these as additional low-confidence "new" items
const LOW_CONFIDENCE_ITEMS: Commitment[] = [
  {
    id: -13,
    hash: "demo-013",
    text: "Look into the slow query on the dashboard page",
    original_quote: "I can take a look at that slow query if I get a chance",
    deadline: null,
    urgency: "low",
    context: "#engineering",
    source_type: "slack",
    confidence: 0.62,
    status: "new",
    direction: "by_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: daysAgo(1),
    snooze_until: null,
    context_summary: "Dashboard page load times spiking due to unoptimized query",
    conversation_messages: msgs(
      ["Pat Johnson", "Dashboard is loading really slowly — some query is taking 3s", false],
      ["You", "I can take a look at that slow query if I get a chance", true],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -2,
    createdAt: daysAgo(1),
  },
  {
    id: -14,
    hash: "demo-014",
    text: "Maybe help with the new hire onboarding guide",
    original_quote: "I could probably help update the onboarding guide sometime",
    deadline: null,
    urgency: "low",
    context: "#people-ops",
    source_type: "slack",
    confidence: 0.55,
    status: "new",
    direction: "by_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: daysAgo(3),
    snooze_until: null,
    context_summary: "People ops looking for volunteers to update new hire docs",
    conversation_messages: msgs(
      ["Maria Chen", "The onboarding guide is really outdated — any volunteers?", false],
      ["You", "I could probably help update the onboarding guide sometime", true],
    ),
    slack_link: null,
    triggered: false,
    sensitive: false,
    tag_id: -6,
    createdAt: daysAgo(3),
  },
];

// ─── Gmail Demo Commitments ───

const GMAIL_COMMITMENTS: Commitment[] = [
  {
    id: -50,
    hash: "demo-050",
    text: "Send revised contract terms to legal team by Thursday",
    original_quote: "I'll get the revised contract terms over to the legal team by Thursday EOD",
    deadline: new Date(Date.now() + 2 * 86400_000).toISOString(),
    urgency: "high",
    context: "Re: Partnership Agreement — Q2 Terms",
    source_type: "gmail",
    confidence: 0.92,
    status: "new",
    direction: "by_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: hoursAgo(5),
    snooze_until: null,
    context_summary: "Email thread with partner company's legal team about updated Q2 contract terms. Requested revised terms before their board meeting.",
    conversation_messages: msgs(
      ["legal@partnerco.com", "Can you send over the revised terms before our board meeting Thursday?", false],
      ["You", "I'll get the revised contract terms over to the legal team by Thursday EOD", true],
    ),
    slack_link: "https://mail.google.com/mail/u/0/#inbox/thread-50",
    triggered: false,
    sensitive: true,
    tag_id: -3,
    createdAt: hoursAgo(5),
  },
  {
    id: -51,
    hash: "demo-051",
    text: "Schedule 1:1 with Alex about performance review feedback",
    original_quote: "I can set up a time to discuss the feedback from your review — let me find a slot this week",
    deadline: new Date(Date.now() + 5 * 86400_000).toISOString(),
    urgency: "medium",
    context: "Re: Q1 Performance Review — Follow-up",
    source_type: "gmail",
    confidence: 0.81,
    status: "new",
    direction: "by_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: hoursAgo(18),
    snooze_until: null,
    context_summary: "Follow-up email from a direct report after their Q1 performance review. They had questions about feedback and growth areas.",
    conversation_messages: msgs(
      ["alex.rodriguez@company.com", "Thanks for the review — I had some questions about the feedback. Can we chat?", false],
      ["You", "I can set up a time to discuss the feedback from your review — let me find a slot this week", true],
    ),
    slack_link: "https://mail.google.com/mail/u/0/#inbox/thread-51",
    triggered: false,
    sensitive: true,
    tag_id: -4,
    createdAt: hoursAgo(18),
  },
  {
    id: -52,
    hash: "demo-052",
    text: "Send conference talk proposal to events team",
    original_quote: "I'll follow up with our talk proposal by next Monday",
    deadline: new Date(Date.now() + 6 * 86400_000).toISOString(),
    urgency: "medium",
    context: "Re: SREcon 2026 — CFP Submission Deadline",
    source_type: "gmail",
    confidence: 0.78,
    status: "new",
    direction: "by_me",
    likely_completed: false,
    completion_signal: null,
    message_timestamp: daysAgo(1),
    snooze_until: null,
    context_summary: "Email from conference organizers about the call for proposals deadline. Committed to submitting a talk proposal on reliability engineering.",
    conversation_messages: msgs(
      ["events@srecon.io", "CFP closes next Friday — have you had a chance to submit your talk proposal?", false],
      ["You", "I'll follow up with our talk proposal by next Monday", true],
    ),
    slack_link: "https://mail.google.com/mail/u/0/#inbox/thread-52",
    triggered: false,
    sensitive: false,
    tag_id: -2,
    createdAt: daysAgo(1),
  },
];

// ─── Derived exports ───

/** Active commitments (new + snoozed with expired snooze) — replaces useCommitments().commitments */
export const DEMO_ACTIVE: Commitment[] = [
  ...DEMO_COMMITMENTS.filter(c => c.status === "new" || c.status === "snoozed"),
  ...LOW_CONFIDENCE_ITEMS,
  ...GMAIL_COMMITMENTS,
];

/** Kanban buckets — replaces useKanban() */
export const DEMO_KANBAN = {
  todo: [...DEMO_COMMITMENTS.filter(c => c.status === "new" || c.status === "snoozed"), ...LOW_CONFIDENCE_ITEMS, ...GMAIL_COMMITMENTS],
  inProgress: DEMO_COMMITMENTS.filter(c => c.status === "actioned"),
  done: DEMO_COMMITMENTS.filter(c => c.status === "done"),
  counts: {
    all: DEMO_COMMITMENTS.filter(c => c.status === "new" || c.status === "snoozed" || c.status === "actioned").length + LOW_CONFIDENCE_ITEMS.length,
    high: DEMO_COMMITMENTS.filter(c => (c.status === "new" || c.status === "snoozed" || c.status === "actioned") && c.urgency === "high").length,
  },
  loading: false,
};

/** Counts for LeftNav — replaces useCommitments().counts */
export const DEMO_COUNTS = {
  all: DEMO_ACTIVE.length,
  high: DEMO_ACTIVE.filter(c => c.urgency === "high").length,
  byMe: DEMO_ACTIVE.filter(c => c.direction === "by_me").length,
  assignedToMe: DEMO_ACTIVE.filter(c => c.direction === "assigned_to_me").length,
};

/** Dismissal patterns */
export const DEMO_DISMISSALS: Dismissal[] = [
  {
    id: -1,
    pattern: "sounds good, I'll take a look",
    reason: "Acknowledgment, not a commitment",
    count: 4,
    createdAt: daysAgo(7),
  },
  {
    id: -2,
    pattern: "let me think about that",
    reason: "Hedging, no concrete action",
    count: 3,
    createdAt: daysAgo(5),
  },
  {
    id: -3,
    pattern: "we should probably do that at some point",
    reason: "Vague aspiration, not actionable",
    count: 2,
    createdAt: daysAgo(3),
  },
];

/** Pending completion suggestions */
export const DEMO_SUGGESTIONS: CompletionSuggestion[] = [
  {
    id: -1,
    commitmentId: -7,
    confidence: 0.82,
    evidence: "Saw 'API docs PR is up for review' in #engineering",
    sourceMessage: "API docs PR is up for review — covers all v2 endpoints",
    status: "pending",
    createdAt: hoursAgo(1),
  },
  {
    id: -2,
    commitmentId: -9,
    confidence: 0.76,
    evidence: "Migration script merged to main",
    sourceMessage: "Migration script merged — running in staging now",
    status: "pending",
    createdAt: hoursAgo(2),
  },
];

/** Today's morning brief */
export const DEMO_BRIEFS: MorningBrief[] = [
  {
    id: -1,
    date: todayDate(),
    greeting: "Good morning! You have 3 high-priority items and a busy afternoon ahead.",
    priorities: [
      {
        commitmentId: -1,
        text: "Send revised proposal to Acme Corp",
        reason: "Due today — Acme expects it before their 5pm meeting",
        suggestedTime: "10:00 AM",
        action: "do",
      },
      {
        commitmentId: -2,
        text: "Review Q2 budget spreadsheet",
        reason: "Board meeting is Thursday — needs sign-off",
        suggestedTime: "11:00 AM",
        action: "do",
      },
      {
        commitmentId: -3,
        text: "Fix authentication bug",
        reason: "Blocking the staging deploy — QA is waiting",
        suggestedTime: "After standup",
        action: "do",
      },
    ],
    scheduleSuggestion: "Tackle the auth bug first since it's blocking others. Then the Acme proposal during your focus block. Review the budget after lunch.",
    headsUp: [
      "The Acme proposal deadline is today at 5pm",
      "Jordan is expecting the customer success deck by Thursday",
    ],
    headsUpTyped: [
      { text: "The Acme proposal deadline is today at 5pm", severity: "due_soon" },
      { text: "Jordan is expecting the customer success deck by Thursday", severity: "warning" },
    ],
    calendarEvents: [
      { title: "Team Standup", start: futureHours(1), end: futureHours(1.5) },
      { title: "Focus Block", start: futureHours(2), end: futureHours(4) },
      { title: "1:1 with Jordan", start: futureHours(5), end: futureHours(5.5) },
    ],
    suggestedMoves: [],
    dismissed: false,
    snoozedUntil: null,
    createdAt: hoursAgo(6),
  },
];

/** Decision log entries */
export const DEMO_DECISION_LOG: DecisionLogEntry[] = [
  {
    id: -1,
    decision: "accepted",
    original_text: "I'll get the revised proposal over to Acme by EOD today",
    sender: "You",
    channel: "#acme-partnership",
    reason: "Send revised proposal to Acme Corp by end of day",
    category: "",
    confidence: 0.94,
    batchId: "demo-batch-1",
    createdAt: hoursAgo(3),
  },
  {
    id: -2,
    decision: "rejected",
    original_text: "Sounds good, will keep an eye on it",
    sender: "You",
    channel: "#engineering",
    reason: "Acknowledgment without concrete action",
    category: "acknowledgment",
    confidence: null,
    batchId: "demo-batch-1",
    createdAt: hoursAgo(3),
  },
  {
    id: -3,
    decision: "accepted",
    original_text: "I'll review the Q2 budget and approve it before the board meeting",
    sender: "You",
    channel: "#finance",
    reason: "Review and approve the Q2 budget spreadsheet",
    category: "",
    confidence: 0.91,
    batchId: "demo-batch-2",
    createdAt: hoursAgo(5),
  },
  {
    id: -4,
    decision: "rejected",
    original_text: "Yeah we should definitely think about that",
    sender: "You",
    channel: "#product",
    reason: "Vague agreement, no specific commitment made",
    category: "hedging",
    confidence: null,
    batchId: "demo-batch-2",
    createdAt: hoursAgo(5),
  },
  {
    id: -5,
    decision: "accepted",
    original_text: "I'll dig into the auth bug right after standup — it's blocking staging",
    sender: "You",
    channel: "#engineering",
    reason: "Fix the authentication bug blocking the staging deploy",
    category: "",
    confidence: 0.88,
    batchId: "demo-batch-3",
    createdAt: hoursAgo(2),
  },
  {
    id: -6,
    decision: "rejected",
    original_text: "Thanks for the heads up, noted",
    sender: "You",
    channel: "#platform-eng",
    reason: "Simple acknowledgment, not a commitment",
    category: "politeness",
    confidence: null,
    batchId: "demo-batch-3",
    createdAt: hoursAgo(2),
  },
  {
    id: -7,
    decision: "rejected",
    original_text: "Sarah mentioned she would update the docs",
    sender: "Pat Johnson",
    channel: "#engineering",
    reason: "Third-party reference — Sarah's commitment, not user's",
    category: "third_party",
    confidence: null,
    batchId: "demo-batch-4",
    createdAt: daysAgo(1),
  },
  {
    id: -8,
    decision: "accepted",
    original_text: "Let me put the competitive analysis together and share it with sales by Friday",
    sender: "You",
    channel: "Q2 Planning Offsite",
    reason: "Share the competitive analysis deck with the sales team",
    category: "",
    confidence: 0.85,
    batchId: "demo-batch-4",
    createdAt: daysAgo(1),
  },
];

// ─── Demo People ───

export const DEMO_PEOPLE: Person[] = [
  {
    id: -1,
    name: "Sarah Chen",
    email: "sarah.chen@company.com",
    relationship: "manager",
    notes: "Meets weekly on Tuesdays. Prefers async updates.",
    commitmentCount: 8,
    lastSeenAt: hoursAgo(2),
    channels: ["#engineering", "1:1 with Sarah"],
    createdAt: daysAgo(30),
  },
  {
    id: -2,
    name: "Mike R.",
    email: "mike.r@company.com",
    relationship: "peer",
    notes: null,
    commitmentCount: 5,
    lastSeenAt: hoursAgo(4),
    channels: ["#engineering", "#platform-eng"],
    createdAt: daysAgo(25),
  },
  {
    id: -3,
    name: "Alex T.",
    email: "alex.t@company.com",
    relationship: "report",
    notes: "Working on onboarding improvements this quarter.",
    commitmentCount: 4,
    lastSeenAt: daysAgo(1),
    channels: ["#product", "1:1 with Alex"],
    createdAt: daysAgo(20),
  },
  {
    id: -4,
    name: "Jordan Lee",
    email: "jordan.lee@company.com",
    relationship: "stakeholder",
    notes: "VP of Sales — key partner for Acme deal.",
    commitmentCount: 6,
    lastSeenAt: hoursAgo(3),
    channels: ["#acme-partnership", "1:1 with Jordan", "Q2 Planning Offsite"],
    createdAt: daysAgo(28),
  },
  {
    id: -5,
    name: "Pat Johnson",
    email: "pat.johnson@company.com",
    relationship: "peer",
    notes: null,
    commitmentCount: 3,
    lastSeenAt: daysAgo(1),
    channels: ["#engineering"],
    createdAt: daysAgo(15),
  },
  {
    id: -6,
    name: "Lisa M.",
    email: "lisa.m@partnerco.com",
    relationship: "external",
    notes: "Acme Corp account manager. Responsive via email.",
    commitmentCount: 2,
    lastSeenAt: daysAgo(3),
    channels: ["#acme-partnership"],
    createdAt: daysAgo(10),
  },
  {
    id: -7,
    name: "Sam Torres",
    email: "sam.torres@company.com",
    relationship: "peer",
    notes: null,
    commitmentCount: 4,
    lastSeenAt: hoursAgo(2),
    channels: ["#engineering"],
    createdAt: daysAgo(22),
  },
  {
    id: -8,
    name: "Dana Park",
    email: "dana.park@company.com",
    relationship: "stakeholder",
    notes: "Product lead — drives roadmap decisions.",
    commitmentCount: 3,
    lastSeenAt: daysAgo(1),
    channels: ["Q2 Planning Offsite", "Product Sync"],
    createdAt: daysAgo(18),
  },
];

// ─── Demo Calendar Events ───

export const DEMO_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: -1,
    googleEventId: "demo-cal-001",
    title: "Team Standup",
    startTime: futureHours(1),
    endTime: futureHours(1.5),
    attendees: ["sarah.chen@company.com", "mike.r@company.com", "sam.torres@company.com"],
    isAllDay: false,
    status: "confirmed",
    fetchedAt: hoursAgo(1),
  },
  {
    id: -2,
    googleEventId: "demo-cal-002",
    title: "1:1 with Sarah",
    startTime: futureHours(3),
    endTime: futureHours(3.5),
    attendees: ["sarah.chen@company.com"],
    isAllDay: false,
    status: "confirmed",
    fetchedAt: hoursAgo(1),
  },
  {
    id: -3,
    googleEventId: "demo-cal-003",
    title: "Sprint Planning",
    startTime: futureHours(5),
    endTime: futureHours(6),
    attendees: ["mike.r@company.com", "pat.johnson@company.com", "alex.t@company.com", "sam.torres@company.com"],
    isAllDay: false,
    status: "confirmed",
    fetchedAt: hoursAgo(1),
  },
  {
    id: -4,
    googleEventId: "demo-cal-004",
    title: "Acme Partnership Review",
    startTime: futureHours(7),
    endTime: futureHours(7.75),
    attendees: ["jordan.lee@company.com", "lisa.m@partnerco.com"],
    isAllDay: false,
    status: "tentative",
    fetchedAt: hoursAgo(1),
  },
  {
    id: -5,
    googleEventId: "demo-cal-005",
    title: "Product Roadmap Sync",
    startTime: futureHours(9),
    endTime: futureHours(9.5),
    attendees: ["dana.park@company.com", "sarah.chen@company.com"],
    isAllDay: false,
    status: "confirmed",
    fetchedAt: hoursAgo(1),
  },
];

// ─── Phase 3: Demo Memories ───

export const DEMO_MEMORIES: MemoryEntry[] = [
  {
    id: -1,
    content: "Prefers deep work before 11am — avoids scheduling meetings in the morning",
    category: "preference",
    importance: 4,
    source: "ai_extraction",
    evidenceIds: [-7, -9],
    lastReinforced: daysAgo(3),
    reinforceCount: 5,
    confirmed: true,
    expiresAt: null,
    createdAt: daysAgo(30),
  },
  {
    id: -2,
    content: "Reports to Jordan Lee (VP Engineering) — weekly 1:1 on Thursdays",
    category: "relationship",
    importance: 5,
    source: "ai_extraction",
    evidenceIds: [-8],
    lastReinforced: daysAgo(1),
    reinforceCount: 8,
    confirmed: true,
    expiresAt: null,
    createdAt: daysAgo(45),
  },
  {
    id: -3,
    content: "Leading the API v2 launch — primary owner of endpoint documentation and migration",
    category: "project",
    importance: 5,
    source: "ai_extraction",
    evidenceIds: [-7, -9],
    lastReinforced: daysAgo(2),
    reinforceCount: 4,
    confirmed: true,
    expiresAt: null,
    createdAt: daysAgo(20),
  },
  {
    id: -4,
    content: "Tends to underestimate time needed for documentation tasks",
    category: "pattern",
    importance: 3,
    source: "pattern_detection",
    evidenceIds: [-7],
    lastReinforced: daysAgo(7),
    reinforceCount: 2,
    confirmed: false,
    expiresAt: null,
    createdAt: daysAgo(14),
  },
  {
    id: -5,
    content: "Uses Grafana for monitoring and prefers dashboard-first observability",
    category: "fact",
    importance: 3,
    source: "ai_extraction",
    evidenceIds: [-5],
    lastReinforced: daysAgo(10),
    reinforceCount: 2,
    confirmed: true,
    expiresAt: null,
    createdAt: daysAgo(25),
  },
  {
    id: -6,
    content: "Q2 board meeting is a major deadline — multiple deliverables converge",
    category: "context",
    importance: 4,
    source: "ai_extraction",
    evidenceIds: [-2, -4],
    lastReinforced: daysAgo(1),
    reinforceCount: 3,
    confirmed: false,
    expiresAt: new Date(Date.now() + 14 * 86400_000).toISOString(),
    createdAt: daysAgo(5),
  },
  {
    id: -7,
    content: "Learned the hard way: always run migration scripts in staging before prod",
    category: "lesson",
    importance: 4,
    source: "user_manual",
    evidenceIds: [],
    lastReinforced: daysAgo(5),
    reinforceCount: 1,
    confirmed: true,
    expiresAt: null,
    createdAt: daysAgo(15),
  },
  {
    id: -8,
    content: "Acme Corp partnership is the highest-priority sales deal this quarter",
    category: "project",
    importance: 5,
    source: "ai_extraction",
    evidenceIds: [-1],
    lastReinforced: daysAgo(1),
    reinforceCount: 6,
    confirmed: true,
    expiresAt: null,
    createdAt: daysAgo(21),
  },
];

// ─── Phase 3: Demo Patterns ───

export const DEMO_PATTERNS: WorkPattern[] = [
  {
    id: -1,
    description: "Completion rate for assigned_to_me items is 55% vs 75% for self-initiated — you may be over-accepting requests from others",
    type: "completion_rate",
    evidenceIds: [-2, -8],
    confidence: 0.78,
    sentiment: "concerning",
    suggestion: "Decline or delegate 2 assigned items this week to bring your completion rate back up",
    acknowledged: false,
    detectedWeek: `${new Date().getFullYear()}-W${String(Math.ceil((Date.now() - new Date(new Date().getFullYear(), 0, 1).getTime()) / (7 * 86400_000))).padStart(2, "0")}`,
    createdAt: daysAgo(1),
  },
  {
    id: -2,
    description: "New commitments this week (12) are 41% above your 4-week average (8.5)",
    type: "overcommitment",
    evidenceIds: [],
    confidence: 0.72,
    sentiment: "concerning",
    suggestion: "Review your open items and snooze or dismiss at least 3 non-urgent ones",
    acknowledged: false,
    detectedWeek: `${new Date().getFullYear()}-W${String(Math.ceil((Date.now() - new Date(new Date().getFullYear(), 0, 1).getTime()) / (7 * 86400_000))).padStart(2, "0")}`,
    createdAt: daysAgo(1),
  },
  {
    id: -3,
    description: "4 of 6 deadlined items completed on time (67% deadline adherence) — consistent with last month",
    type: "deadline_adherence",
    evidenceIds: [],
    confidence: 0.85,
    sentiment: "neutral",
    suggestion: null,
    acknowledged: false,
    detectedWeek: `${new Date().getFullYear()}-W${String(Math.ceil((Date.now() - new Date(new Date().getFullYear(), 0, 1).getTime()) / (7 * 86400_000))).padStart(2, "0")}`,
    createdAt: daysAgo(1),
  },
  {
    id: -4,
    description: "Engineering tasks (#engineering) have the fastest turnaround at 1.2 days avg vs 6.1 days for hiring-related items",
    type: "time_allocation",
    evidenceIds: [],
    confidence: 0.9,
    sentiment: "positive",
    suggestion: null,
    acknowledged: false,
    detectedWeek: `${new Date().getFullYear()}-W${String(Math.ceil((Date.now() - new Date(new Date().getFullYear(), 0, 1).getTime()) / (7 * 86400_000))).padStart(2, "0")}`,
    createdAt: daysAgo(1),
  },
];

// ─── Phase 3: Demo Weekly Digests ───

export const DEMO_DIGESTS: WeeklyDigest[] = [
  {
    id: -1,
    weekStart: new Date(Date.now() - ((new Date().getDay() + 6) % 7) * 86400_000).toISOString().slice(0, 10),
    completed: 5,
    added: 12,
    overdue: 3,
    patterns: DEMO_PATTERNS,
    summary: "A busy week with 12 new commitments — above your usual average. You completed 5 items including the a11y fixes merge and the product sync notes. Three items are now overdue, including the monitoring dashboard setup. Your engineering work stayed sharp but hiring-related tasks continued to lag.",
    suggestedFocus: [
      "Close out the overdue monitoring dashboard setup",
      "Review and triage assigned items — completion rate is slipping",
      "Block time for the API docs before the sprint ends",
    ],
    createdAt: daysAgo(1),
  },
];

// ─── Phase 3: Demo OKRs ───

export const DEMO_OKRS: OKR[] = [
  {
    id: -1,
    objective: "Ship API v2 to production",
    keyResults: [
      { text: "All v2 endpoints documented and reviewed", progress: 60 },
      { text: "User table migration complete and validated", progress: 40 },
      { text: "Zero P0 bugs in staging for 5 consecutive days", progress: 20 },
    ],
    period: `${new Date().getFullYear()}-Q${Math.ceil((new Date().getMonth() + 1) / 3)}`,
    rank: 1,
    alignedCount: 4,
    source: "user",
    active: true,
    createdAt: daysAgo(30),
  },
  {
    id: -2,
    objective: "Close Acme Corp partnership",
    keyResults: [
      { text: "Revised proposal sent and accepted", progress: 30 },
      { text: "Legal review of contract terms completed", progress: 10 },
      { text: "Partnership announcement published", progress: 0 },
    ],
    period: `${new Date().getFullYear()}-Q${Math.ceil((new Date().getMonth() + 1) / 3)}`,
    rank: 2,
    alignedCount: 3,
    source: "user",
    active: true,
    createdAt: daysAgo(25),
  },
  {
    id: -3,
    objective: "Improve platform reliability",
    keyResults: [
      { text: "Production monitoring dashboard live", progress: 50 },
      { text: "CI pipeline includes new linting rules", progress: 100 },
      { text: "On-call response time under 15 minutes", progress: 70 },
    ],
    period: `${new Date().getFullYear()}-Q${Math.ceil((new Date().getMonth() + 1) / 3)}`,
    rank: 3,
    alignedCount: 3,
    source: "ai_suggested",
    active: true,
    createdAt: daysAgo(20),
  },
];

// ─── Phase 3: Demo OKR Links ───

export const DEMO_OKR_LINKS: CommitmentOKRLink[] = [
  { id: -1, commitmentId: -7, okrId: -1, alignment: "directly_supports", source: "ai", createdAt: daysAgo(3) },
  { id: -2, commitmentId: -9, okrId: -1, alignment: "directly_supports", source: "ai", createdAt: daysAgo(2) },
  { id: -3, commitmentId: -3, okrId: -1, alignment: "indirectly_supports", source: "ai", createdAt: daysAgo(1) },
  { id: -4, commitmentId: -10, okrId: -1, alignment: "directly_supports", source: "ai", createdAt: daysAgo(1) },
  { id: -5, commitmentId: -1, okrId: -2, alignment: "directly_supports", source: "ai", createdAt: daysAgo(1) },
  { id: -6, commitmentId: -50, okrId: -2, alignment: "directly_supports", source: "ai", createdAt: daysAgo(1) },
  { id: -7, commitmentId: -4, okrId: -2, alignment: "indirectly_supports", source: "ai", createdAt: daysAgo(1) },
  { id: -8, commitmentId: -5, okrId: -3, alignment: "directly_supports", source: "ai", createdAt: daysAgo(2) },
  { id: -9, commitmentId: -12, okrId: -3, alignment: "directly_supports", source: "ai", createdAt: daysAgo(3) },
  { id: -10, commitmentId: -8, okrId: -3, alignment: "indirectly_supports", source: "ai", createdAt: daysAgo(2) },
];

// ─── Phase 2: Demo Action Proposals ───

export const DEMO_ACTION_PROPOSALS: ActionProposal[] = [
  {
    id: -1,
    commitmentId: -1,
    type: "send_message",
    status: "pending",
    description: "Send follow-up to Jordan in #acme-partnership about proposal status",
    payload: JSON.stringify({ platform: "slack", recipient: "#acme-partnership", subject: null, draftId: -1 }),
    resultMessage: null,
    errorMessage: null,
    source: "follow_up_engine",
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
  {
    id: -2,
    commitmentId: -3,
    type: "block_time",
    status: "pending",
    description: "Block 1 hour to work on the authentication bug",
    payload: JSON.stringify({ commitmentId: -3, commitmentText: "Fix the auth bug", deadline: null, durationMinutes: 60 }),
    resultMessage: null,
    errorMessage: null,
    source: "clyde_chat",
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
  },
];

// ─── Phase 2: Demo Drafts ───

export const DEMO_DRAFTS: DraftMessage[] = [
  {
    id: -1,
    commitmentId: -1,
    proposalId: -1,
    platform: "slack",
    recipient: "#acme-partnership",
    subject: null,
    body: "Hi Jordan — just following up on the revised Acme proposal I sent over last week. Let me know if you need any changes before today's 5pm deadline.",
    tone: "professional",
    status: "pending",
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
];

// ─── Phase 2: Demo Follow-Up Rules ───

export const DEMO_FOLLOW_UP_RULES: FollowUpRule[] = [
  {
    id: -1,
    commitmentId: -4,
    checkAt: new Date(Date.now() + 24 * 3600_000).toISOString(),
    fireCount: 0,
    status: "active",
    createdAt: daysAgo(1),
  },
];

// ─── Phase 5: Demo Jira Tickets ───

export const DEMO_JIRA_TICKETS: JiraTicket[] = [
  {
    key: "RAD-8231",
    summary: "Add real-time collaboration cursors to canvas",
    status: "Done",
    statusCategory: "done",
    issueType: "Story",
    component: "Collab App",
    priority: "High",
    epicKey: "RAD-8000",
    projectKey: "RAD",
    assigneeEmail: "alice@example.com",
    assigneeDisplayName: "Alice Chen",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-03-01T14:30:00Z",
    resolvedAt: "2026-03-01T14:30:00Z",
    syncedAt: "2026-03-18T00:00:00Z",
  },
  {
    key: "RAD-8245",
    summary: "Fix cursor position drift on zoom",
    status: "Done",
    statusCategory: "done",
    issueType: "Bug",
    component: "Collab App",
    priority: "High",
    epicKey: "RAD-8000",
    projectKey: "RAD",
    assigneeEmail: "alice@example.com",
    assigneeDisplayName: "Alice Chen",
    createdAt: "2026-02-20T09:00:00Z",
    updatedAt: "2026-03-05T11:00:00Z",
    resolvedAt: "2026-03-05T11:00:00Z",
    syncedAt: "2026-03-18T00:00:00Z",
  },
  {
    key: "RAD-8260",
    summary: "Migrate progress tracking to new API v3",
    status: "Merged",
    statusCategory: "in_progress",
    issueType: "Task",
    component: "Progress Tracking",
    priority: "Medium",
    epicKey: null,
    projectKey: "RAD",
    assigneeEmail: "bob@example.com",
    assigneeDisplayName: "Bob Martinez",
    createdAt: "2026-02-25T08:00:00Z",
    updatedAt: "2026-03-10T16:00:00Z",
    resolvedAt: null,
    syncedAt: "2026-03-18T00:00:00Z",
  },
  {
    key: "RAD-8275",
    summary: "Add GraphQL subscriptions for live updates",
    status: "Done",
    statusCategory: "done",
    issueType: "New Feature",
    component: "BE Guild",
    priority: "High",
    epicKey: "RAD-8100",
    projectKey: "RAD",
    assigneeEmail: "bob@example.com",
    assigneeDisplayName: "Bob Martinez",
    createdAt: "2026-02-28T10:00:00Z",
    updatedAt: "2026-03-12T09:30:00Z",
    resolvedAt: "2026-03-12T09:30:00Z",
    syncedAt: "2026-03-18T00:00:00Z",
  },
  {
    key: "RAD-8290",
    summary: "Optimize database queries for progress reports",
    status: "Code Review",
    statusCategory: "in_progress",
    issueType: "Task",
    component: "BE Guild",
    priority: "Medium",
    epicKey: null,
    projectKey: "RAD",
    assigneeEmail: "carol@example.com",
    assigneeDisplayName: "Carol Singh",
    createdAt: "2026-03-01T14:00:00Z",
    updatedAt: "2026-03-15T10:00:00Z",
    resolvedAt: null,
    syncedAt: "2026-03-18T00:00:00Z",
  },
  {
    key: "RAD-8310",
    summary: "Student progress dashboard redesign",
    status: "Done",
    statusCategory: "done",
    issueType: "Story",
    component: "Progress Tracking",
    priority: "High",
    epicKey: "RAD-8200",
    projectKey: "RAD",
    assigneeEmail: "carol@example.com",
    assigneeDisplayName: "Carol Singh",
    createdAt: "2026-03-03T09:00:00Z",
    updatedAt: "2026-03-14T17:00:00Z",
    resolvedAt: "2026-03-14T17:00:00Z",
    syncedAt: "2026-03-18T00:00:00Z",
  },
  {
    key: "RAD-8325",
    summary: "Fix OAuth token refresh race condition",
    status: "Done",
    statusCategory: "done",
    issueType: "Bug",
    component: "BE Guild",
    priority: "High",
    epicKey: null,
    projectKey: "RAD",
    assigneeEmail: "alice@example.com",
    assigneeDisplayName: "Alice Chen",
    createdAt: "2026-03-05T11:00:00Z",
    updatedAt: "2026-03-08T15:00:00Z",
    resolvedAt: "2026-03-08T15:00:00Z",
    syncedAt: "2026-03-18T00:00:00Z",
  },
  {
    key: "RAD-8340",
    summary: "Add bulk assignment UI for teachers",
    status: "Backlog",
    statusCategory: "todo",
    issueType: "Story",
    component: "Collab App",
    priority: "Medium",
    epicKey: "RAD-8200",
    projectKey: "RAD",
    assigneeEmail: null,
    assigneeDisplayName: null,
    createdAt: "2026-03-08T10:00:00Z",
    updatedAt: "2026-03-08T10:00:00Z",
    resolvedAt: null,
    syncedAt: "2026-03-18T00:00:00Z",
  },
  {
    key: "RAD-8355",
    summary: "Implement SSO for enterprise customers",
    status: "Backlog",
    statusCategory: "todo",
    issueType: "New Feature",
    component: null,
    priority: "Medium",
    epicKey: "RAD-8300",
    projectKey: "RAD",
    assigneeEmail: null,
    assigneeDisplayName: null,
    createdAt: "2026-03-10T09:00:00Z",
    updatedAt: "2026-03-10T09:00:00Z",
    resolvedAt: null,
    syncedAt: "2026-03-18T00:00:00Z",
  },
  {
    key: "RAD-8370",
    summary: "Update CI pipeline to use Node 22",
    status: "Done",
    statusCategory: "done",
    issueType: "Task",
    component: null,
    priority: "Low",
    epicKey: null,
    projectKey: "RAD",
    assigneeEmail: "bob@example.com",
    assigneeDisplayName: "Bob Martinez",
    createdAt: "2026-03-12T08:00:00Z",
    updatedAt: "2026-03-13T12:00:00Z",
    resolvedAt: "2026-03-13T12:00:00Z",
    syncedAt: "2026-03-18T00:00:00Z",
  },
];

// ─── Phase 5: Demo PR-Jira Links ───

export const DEMO_PR_JIRA_LINKS: PRJiraLink[] = [
  { prMetricId: 1, jiraTicketKey: "RAD-8231", source: "title", linkedAt: "2026-03-18T00:00:00Z" },
  { prMetricId: 2, jiraTicketKey: "RAD-8245", source: "title", linkedAt: "2026-03-18T00:00:00Z" },
  { prMetricId: 3, jiraTicketKey: "RAD-8260", source: "branch", linkedAt: "2026-03-18T00:00:00Z" },
  { prMetricId: 4, jiraTicketKey: "RAD-8275", source: "title", linkedAt: "2026-03-18T00:00:00Z" },
  { prMetricId: 5, jiraTicketKey: "RAD-8290", source: "title", linkedAt: "2026-03-18T00:00:00Z" },
  { prMetricId: 6, jiraTicketKey: "RAD-8310", source: "title", linkedAt: "2026-03-18T00:00:00Z" },
  { prMetricId: 7, jiraTicketKey: "RAD-8325", source: "branch", linkedAt: "2026-03-18T00:00:00Z" },
];

// ─── Demo People Context ───

export const DEMO_PEOPLE_CONTEXT: PersonContext[] = [
  {
    personId: -1,
    completionRate: 0.75,
    overdueRate: 0.12,
    avgResponseDays: 1.2,
    totalCommitments: 8,
    openCommitments: 2,
    completedCommitments: 6,
    dismissedCommitments: 0,
    topChannels: ["#engineering", "1:1 with Sarah", "#platform-eng"],
    lastInteractionSummary: "Review Q2 roadmap priorities with product team",
    computedAt: hoursAgo(2),
  },
  {
    personId: -2,
    completionRate: 0.60,
    overdueRate: 0.20,
    avgResponseDays: 2.5,
    totalCommitments: 5,
    openCommitments: 2,
    completedCommitments: 3,
    dismissedCommitments: 0,
    topChannels: ["#engineering", "#platform-eng"],
    lastInteractionSummary: "Finalize API rate limiting design doc",
    computedAt: hoursAgo(2),
  },
  {
    personId: -3,
    completionRate: 0.50,
    overdueRate: 0.25,
    avgResponseDays: 3.0,
    totalCommitments: 4,
    openCommitments: 2,
    completedCommitments: 2,
    dismissedCommitments: 0,
    topChannels: ["#product", "1:1 with Alex"],
    lastInteractionSummary: "Complete onboarding flow redesign mockups",
    computedAt: hoursAgo(2),
  },
  {
    personId: -4,
    completionRate: 0.83,
    overdueRate: 0.0,
    avgResponseDays: 0.8,
    totalCommitments: 6,
    openCommitments: 1,
    completedCommitments: 5,
    dismissedCommitments: 0,
    topChannels: ["#acme-partnership", "1:1 with Jordan", "Q2 Planning Offsite"],
    lastInteractionSummary: "Send updated proposal to Acme by Friday",
    computedAt: hoursAgo(2),
  },
  {
    personId: -5,
    completionRate: 0.67,
    overdueRate: 0.33,
    avgResponseDays: 4.0,
    totalCommitments: 3,
    openCommitments: 1,
    completedCommitments: 2,
    dismissedCommitments: 0,
    topChannels: ["#engineering"],
    lastInteractionSummary: "Set up staging environment for load tests",
    computedAt: hoursAgo(2),
  },
];

// ─── AI News Demo Posts ───

export const DEMO_NEWS_POSTS: NewsPost[] = [
  {
    id: -100,
    sourceId: "anthropic-blog:claude-code-worktrees",
    source: "anthropic-blog",
    sourceName: "Anthropic Blog",
    author: null,
    title: "Claude Code Now Supports Multi-Repo Worktrees",
    rawText: "Today we're shipping worktree isolation in Claude Code, letting developers run parallel tasks across repos without git conflicts.",
    summary: "Claude Code adds worktree isolation for parallel development tasks, eliminating git conflicts when working across multiple features simultaneously.",
    relevanceScore: 10,
    topicTag: "Claude & Anthropic",
    postedAt: hoursAgo(2),
    url: "https://www.anthropic.com/news/claude-code-worktrees",
    fetchedAt: hoursAgo(1),
    readAt: null,
    bookmarked: true,
  },
  {
    id: -101,
    sourceId: "hacker-news:42001234",
    source: "hacker-news",
    sourceName: "Hacker News",
    author: "pgrzesik",
    title: "Show HN: Open-source agent framework for production workflows hits 10k stars",
    rawText: "Show HN: Open-source agent framework for production workflows hits 10k stars",
    summary: "An open-source agentic framework designed for production reliability reaches 10k GitHub stars, featuring built-in observability and human-in-the-loop patterns.",
    relevanceScore: 8,
    topicTag: "Agents & Workflows",
    postedAt: hoursAgo(5),
    url: "https://news.ycombinator.com/item?id=42001234",
    fetchedAt: hoursAgo(1),
    readAt: hoursAgo(1),
    bookmarked: false,
  },
  {
    id: -102,
    sourceId: "arxiv:2403.12345",
    source: "arxiv",
    sourceName: "arXiv AI",
    author: "Chen et al.",
    title: "Scaling Laws for Agentic Tool Use in Large Language Models",
    rawText: "We present the first systematic study of how tool-use capabilities scale with model size, training data, and inference compute in agentic settings.",
    summary: "First systematic study of agentic tool-use scaling laws finds that tool accuracy scales log-linearly with model size but shows phase transitions at certain capability thresholds.",
    relevanceScore: 9,
    topicTag: "Research",
    postedAt: hoursAgo(8),
    url: "https://arxiv.org/abs/2403.12345",
    fetchedAt: hoursAgo(1),
    readAt: null,
    bookmarked: true,
  },
  {
    id: -103,
    sourceId: "verge-ai:gemini-25-launch",
    source: "verge-ai",
    sourceName: "The Verge AI",
    author: "James Vincent",
    title: "Google Announces Gemini 2.5 with Native Code Execution",
    rawText: "Google's latest model can write and run code in a sandboxed environment during inference, a significant step toward autonomous coding agents.",
    summary: "Gemini 2.5 introduces native sandboxed code execution during inference, signaling Google's push into autonomous coding agents.",
    relevanceScore: 7,
    topicTag: "Industry",
    postedAt: daysAgo(1),
    url: "https://www.theverge.com/2024/gemini-25-code-execution",
    fetchedAt: hoursAgo(1),
    readAt: hoursAgo(3),
    bookmarked: false,
  },
  {
    id: -104,
    sourceId: "openai-blog:structured-outputs-v2",
    source: "openai-blog",
    sourceName: "OpenAI Blog",
    author: null,
    title: "New GPT-5 API Endpoints for Structured Outputs",
    rawText: "We're launching new API endpoints that guarantee JSON schema conformance in GPT-5 outputs, with support for complex nested schemas and union types.",
    summary: "OpenAI launches guaranteed JSON schema conformance for GPT-5 API outputs, supporting complex nested schemas and union types.",
    relevanceScore: 6,
    topicTag: "Tools & Infra",
    postedAt: daysAgo(1),
    url: "https://openai.com/blog/structured-outputs-v2",
    fetchedAt: hoursAgo(1),
    readAt: hoursAgo(2),
    bookmarked: false,
  },
  {
    id: -105,
    sourceId: "huggingface-blog:open-coder-bench",
    source: "huggingface-blog",
    sourceName: "Hugging Face Blog",
    author: "Leandro von Werra",
    title: "Open Weights Model Beats GPT-4 on Coding Benchmarks",
    rawText: "The latest open-weights coding model achieves state-of-the-art on HumanEval and SWE-Bench, matching proprietary model performance.",
    summary: "A new open-weights model matches GPT-4 on HumanEval and SWE-Bench coding benchmarks, narrowing the open/closed source capability gap.",
    relevanceScore: 7,
    topicTag: "Open Source",
    postedAt: daysAgo(2),
    url: "https://huggingface.co/blog/open-coder-bench",
    fetchedAt: hoursAgo(1),
    readAt: null,
    bookmarked: false,
  },
  {
    id: -106,
    sourceId: "techcrunch-ai:anthropic-series-e",
    source: "techcrunch-ai",
    sourceName: "TechCrunch AI",
    author: "Kyle Wiggers",
    title: "Anthropic Raises $5B Series E at $60B Valuation",
    rawText: "Anthropic has closed a $5 billion Series E round led by Lightspeed Venture Partners, valuing the AI safety company at $60 billion.",
    summary: "Anthropic closes $5B Series E at $60B valuation, led by Lightspeed. Funding will accelerate Claude model development and enterprise infrastructure.",
    relevanceScore: 8,
    topicTag: "Claude & Anthropic",
    postedAt: daysAgo(2),
    url: "https://techcrunch.com/anthropic-series-e",
    fetchedAt: hoursAgo(1),
    readAt: null,
    bookmarked: false,
  },
  {
    id: -107,
    sourceId: "anthropic-blog:claude-code-review",
    source: "anthropic-blog",
    sourceName: "Anthropic Blog",
    author: null,
    title: "Introducing Claude Code Review: AI-Powered PR Analysis",
    rawText: "Claude Code Review automatically analyzes pull requests for bugs, security issues, and style consistency, integrating directly with GitHub.",
    summary: "Anthropic launches Claude Code Review for automated PR analysis covering bugs, security, and style — integrates directly with GitHub workflows.",
    relevanceScore: 10,
    topicTag: "Claude & Anthropic",
    postedAt: daysAgo(3),
    url: "https://www.anthropic.com/news/claude-code-review",
    fetchedAt: hoursAgo(1),
    readAt: hoursAgo(6),
    bookmarked: false,
  },
];

export const DEMO_NEWS_BRIEFING = `\u2022 Anthropic ships worktree isolation in Claude Code and launches Claude Code Review for automated PR analysis
\u2022 New research on agentic tool-use scaling laws shows phase transitions at capability thresholds — implications for when to upgrade models
\u2022 Open-source coding models closing the gap with proprietary ones on HumanEval and SWE-Bench
\u2022 Google and OpenAI both pushing toward autonomous code execution in their latest model releases
\u2022 Anthropic's $5B raise signals continued investment in Claude enterprise infrastructure`;

export const DEMO_OPEN_PR_SNAPSHOTS: OpenPRSnapshot[] = [
  { id: 1, repo: "openspace-ai/diana", openCount: 42, snapshotAt: daysAgo(7) },
  { id: 2, repo: "openspace-ai/rad", openCount: 38, snapshotAt: daysAgo(7) },
  { id: 3, repo: "openspace-ai/diana", openCount: 45, snapshotAt: daysAgo(3) },
  { id: 4, repo: "openspace-ai/rad", openCount: 40, snapshotAt: daysAgo(3) },
  { id: 5, repo: "openspace-ai/diana", openCount: 48, snapshotAt: hoursAgo(6) },
  { id: 6, repo: "openspace-ai/rad", openCount: 41, snapshotAt: hoursAgo(6) },
];

export const DEMO_PR_INBOX: PRInboxItem[] = [
  {
    id: 1001,
    number: 342,
    title: "Fix race condition in webhook retry logic",
    html_url: "https://github.com/openspace-ai/diana/pull/342",
    repo: "openspace-ai/diana",
    author: "samlee",
    authorAvatar: "https://avatars.githubusercontent.com/u/1?v=4",
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(1),
    isDraft: false,
    reason: "review-requested",
    labels: [{ name: "bug", color: "d73a4a" }],
  },
  {
    id: 1002,
    number: 789,
    title: "Add shared asset drone transfer API endpoint",
    html_url: "https://github.com/openspace-ai/rad/pull/789",
    repo: "openspace-ai/rad",
    author: "jcheng",
    authorAvatar: "https://avatars.githubusercontent.com/u/2?v=4",
    createdAt: hoursAgo(18),
    updatedAt: hoursAgo(4),
    isDraft: false,
    reason: "review-requested",
    labels: [{ name: "feature", color: "0075ca" }, { name: "backend", color: "5319e7" }],
  },
  {
    id: 1003,
    number: 156,
    title: "Migrate auth middleware to new compliance token format",
    html_url: "https://github.com/openspace-ai/diana/pull/156",
    repo: "openspace-ai/diana",
    author: "mrodriguez",
    authorAvatar: "https://avatars.githubusercontent.com/u/3?v=4",
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(8),
    isDraft: false,
    reason: "assigned",
    labels: [{ name: "compliance", color: "fbca04" }],
  },
  {
    id: 1004,
    number: 91,
    title: "[WIP] Experiment with voxel terrain generation for Story Islands",
    html_url: "https://github.com/openspace-ai/storyworld/pull/91",
    repo: "openspace-ai/storyworld",
    author: "ktan",
    authorAvatar: "https://avatars.githubusercontent.com/u/4?v=4",
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(12),
    isDraft: true,
    reason: "mentioned",
    labels: [],
  },
  {
    id: 1005,
    number: 445,
    title: "Bump CDR pipeline timeout to handle Suffolk batch sizes",
    html_url: "https://github.com/openspace-ai/rad/pull/445",
    repo: "openspace-ai/rad",
    author: "apark",
    authorAvatar: "https://avatars.githubusercontent.com/u/5?v=4",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    isDraft: false,
    reason: "assigned",
    labels: [{ name: "infra", color: "006b75" }],
  },
];

